### ISSUE TITLE
modal generation problem

### ISSUE THREAD

**Issue by ainilife** [unidal/frameworks#2]
对于boolean类型的值，每次都生成两个方法：isXXX() 和 getXXX()，这个object在使用jackthon的时候就会不work了。会报错。建议只生成一个方法，isXXX()。

例如：

"Could not write content: Conflicting getter definitions for property "forceWriteOnLogin": com.dianping.zebra.group.config.datasource.entity.GroupDataSourceConfig#isForceWriteOnLogin(0 params) vs com.dianping.zebra.group.config.datasource.entity.GroupDataSourceConfig#getForceWriteOnLogin(0 params) (through reference chain: com.dianping.zebra.admin.dto.ConnectStatusDto["groupDataSourceConfig"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Conflicting getter definitions for property "forceWriteOnLogin": com.dianping.zebra.group.config.datasource.entity.GroupDataSourceConfig#isForceWriteOnLogin(0 params) vs com.dianping.zebra.group.config.datasource.entity.GroupDataSourceConfig#getForceWriteOnLogin(0 params) (through reference chain: com.dianping.zebra.admin.dto.ConnectStatusDto["groupDataSourceConfig"])"

**Comment by qmwu2000** [comment]
使用primitive="true"就可以了。

**Comment by ainilife** [comment]
原来如此，嘿嘿。
