### ISSUE TITLE
framework可以更新下么

### ISSUE THREAD

**Issue by copoo** [unidal/frameworks#3]
吴老师，您好，在cat支持java8的fix提交上，有看到framework已经更新到2.3.0了，但现有可以拿到的仍是3年前的代码。之前在调研cat java 8支持的时候，发现依赖的根源是framewok中使用的plexus容器，所以花了一段时间在看framwork的东西，但是还是仍未解决。请问framework和maven的代码可以开源并更新下么，让我们学习一下，谢谢了。

**Comment by qmwu2000** [comment]
http://github.com/unidal/frameworks


发自我的 iPhone

**Comment by copoo** [comment]
谢谢吴老师，是否是webres也修改了，cat中测试用例使用到的jettyserver（在testfwk）中貌似不能用了

**Comment by qmwu2000** [comment]
webres没有修改。


发自我的 iPhone
